name: pinjemlah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  cookie_jar: ^4.0.8
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  network_info_plus: ^5.0.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon1.png"
  adaptive_icon_background: "#5E17EB"
  adaptive_icon_foreground: "assets/icon2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.svg
    - assets/logo2.svg
    - assets/
